const KEY="bakely-pos-v1";
const seed={products:[
{id:"CK-001",name:"Classic Chocolate Chip Cookies",cat:"Cookie",collection:"BAKELY Classics",status:"ACTIVE",version:"V1.0",cost:3.12,price:12,effort:3,qc:96,units:120},
{id:"CK-002",name:"Double Chocolate Cookies",cat:"Cookie",collection:"Chocolate Edit",status:"DEVELOPMENT",version:"V0.3",cost:3.45,price:13,effort:4,qc:92,units:80},
{id:"CK-003",name:"Nutty Delight Cookies",cat:"Cookie",collection:"BAKELY Classics",status:"ACTIVE",version:"V1.1",cost:3.30,price:13,effort:3,qc:94,units:70},
{id:"CK-004",name:"Red Velvet Cookies",cat:"Cookie",collection:"Signature",status:"TESTING",version:"V0.8",cost:3.30,price:13,effort:4,qc:91,units:60},
{id:"CK-005",name:"Oatmeal Raisin Cookies",cat:"Cookie",collection:"BAKELY Classics",status:"ACTIVE",version:"V1.0",cost:2.65,price:11,effort:2,qc:95,units:90},
{id:"BX-001",name:"Assorted Cookie Box",cat:"Gift Box",collection:"Gifting",status:"ACTIVE",version:"V1.0",cost:11.20,price:28,effort:3,qc:97,units:35},
{id:"BW-001",name:"Signature Brownie Box",cat:"Brownie",collection:"Brownie Moments",status:"ACTIVE",version:"V1.2",cost:7.15,price:26,effort:3,qc:96,units:50},
{id:"BW-002",name:"Dark Chocolate Brownies",cat:"Brownie",collection:"Brownie Moments",status:"ACTIVE",version:"V1.0",cost:6.60,price:24,effort:3,qc:95,units:40},
{id:"GB-001",name:"Mixed Treat Gift Box",cat:"Gift Box",collection:"Gifting",status:"ACTIVE",version:"V1.0",cost:15.40,price:38,effort:4,qc:98,units:20},
{id:"GB-002",name:"Celebration Gift Box",cat:"Gift Box",collection:"Gifting",status:"SEASONAL",version:"V0.9",cost:19.10,price:48,effort:4,qc:97,units:18}],
ingredients:[
{id:"ING-001",name:"All-purpose flour",unit:"g",pack:25000,price:28,supplier:"BAKELY Ingredients Co.",stock:18000,min:5000},
{id:"ING-002",name:"Unsalted butter",unit:"g",pack:5000,price:52,supplier:"Golden Dairy Partners",stock:4200,min:2500},
{id:"ING-003",name:"Brown sugar",unit:"g",pack:10000,price:24,supplier:"BAKELY Ingredients Co.",stock:7200,min:2500},
{id:"ING-004",name:"Dark chocolate",unit:"g",pack:10000,price:91,supplier:"Premium Cocoa Supply",stock:1700,min:2500},
{id:"ING-005",name:"White sugar",unit:"g",pack:10000,price:20,supplier:"BAKELY Ingredients Co.",stock:6800,min:2000},
{id:"ING-006",name:"Eggs",unit:"unit",pack:360,price:58,supplier:"Golden Dairy Partners",stock:96,min:120},
{id:"ING-007",name:"Vanilla extract",unit:"ml",pack:1000,price:34,supplier:"BAKELY Ingredients Co.",stock:620,min:250},
{id:"ING-008",name:"Cocoa powder",unit:"g",pack:5000,price:46,supplier:"Premium Cocoa Supply",stock:2100,min:1200},
{id:"ING-009",name:"Walnuts",unit:"g",pack:5000,price:62,supplier:"Artisan Nuts & More",stock:800,min:1200},
{id:"ING-010",name:"Oats",unit:"g",pack:10000,price:22,supplier:"BAKELY Ingredients Co.",stock:4300,min:2000}],
suppliers:[
{id:"SUP-001",name:"BAKELY Ingredients Co.",contact:"Maya Shah",email:"orders@example.com",lead:"2 days",terms:"Net 15",status:"ACTIVE"},
{id:"SUP-002",name:"Premium Cocoa Supply",contact:"Daniel Reed",email:"sales@example.com",lead:"4 days",terms:"Net 30",status:"ACTIVE"},
{id:"SUP-003",name:"Golden Dairy Partners",contact:"Aisha Khan",email:"hello@example.com",lead:"1 day",terms:"Net 15",status:"ACTIVE"},
{id:"SUP-004",name:"Artisan Nuts & More",contact:"Liam Chen",email:"orders@example.com",lead:"3 days",terms:"Prepaid",status:"ACTIVE"},
{id:"SUP-005",name:"SweetPack Packaging",contact:"Nora Ali",email:"pack@example.com",lead:"5 days",terms:"Net 30",status:"ACTIVE"}],
recipes:[
{id:"RCP-001",product:"CK-001",version:"V1.0",status:"APPROVED",yield:10,unitWeight:75,ingredients:[["ING-001",500],["ING-002",300],["ING-003",200],["ING-005",125],["ING-006",2],["ING-007",10],["ING-004",250]],method:["Prepare ingredients.","Cream butter and sugars.","Add eggs and vanilla.","Fold in dry ingredients.","Add chocolate.","Portion at 75g.","Chill 30 minutes.","Bake at 175°C for 12 minutes.","Cool completely.","Package."],created:"2026-09-20",reason:"Approved production standard"},
{id:"RCP-002",product:"CK-002",version:"V0.3",status:"TESTING",yield:10,unitWeight:75,ingredients:[["ING-001",480],["ING-002",310],["ING-003",180],["ING-008",70],["ING-004",300],["ING-006",2]],method:["Cream butter and sugar.","Add eggs.","Mix dry ingredients.","Add cocoa and chocolate.","Portion.","Bake at 170°C for 11 minutes."],created:"2026-09-21",reason:"Testing darker cocoa profile"}],
batches:[
{id:"BAT-1048",product:"CK-001",recipe:"V1.0",qty:120,baker:"Baker A",date:"2026-09-22",status:"AWAITING_QC",yield:118,waste:2},
{id:"BAT-1049",product:"CK-002",recipe:"V0.3",qty:80,baker:"Baker B",date:"2026-09-22",status:"IN_PROGRESS",yield:0,waste:0},
{id:"BAT-1050",product:"BW-001",recipe:"V1.2",qty:50,baker:"Baker A",date:"2026-09-23",status:"PLANNED",yield:0,waste:0}],
plans:[
{id:"PLAN-2209",date:"2026-09-22",product:"CK-001",qty:120,baker:"Baker A",due:"12:00",status:"AWAITING_QC",priority:"High"},
{id:"PLAN-2210",date:"2026-09-22",product:"CK-002",qty:80,baker:"Baker B",due:"14:00",status:"IN_PROGRESS",priority:"Normal"},
{id:"PLAN-2211",date:"2026-09-23",product:"BW-001",qty:50,baker:"Baker A",due:"11:00",status:"PLANNED",priority:"Normal"}],
qc:[
{id:"QC-1048",batch:"BAT-1048",product:"CK-001",score:96,status:"PENDING",tester:"Production Manager",notes:"Awaiting final sign-off"},
{id:"QC-1047",batch:"BAT-1047",product:"BW-001",score:97,status:"PASSED",tester:"Production Manager",notes:"Excellent texture"},
{id:"QC-1046",batch:"BAT-1046",product:"CK-003",score:94,status:"PASSED",tester:"Baker A",notes:"Minor shape variation"}],
photos:[
{id:"PH-001",product:"CK-001",type:"Hero",caption:"Classic Chocolate Chip — approved visual standard"},
{id:"PH-002",product:"BW-001",type:"Packaging",caption:"Signature Brownie Box"},
{id:"PH-003",product:"GB-001",type:"Gift",caption:"Mixed Treat Gift Box"}],
audit:[
{time:"2026-09-22 10:42",user:"Owner",action:"Approved CK-001 Recipe V1.0",type:"APPROVE"},
{time:"2026-09-22 09:30",user:"Finance",action:"Updated dark chocolate supplier price",type:"PRICE_CHANGE"},
{time:"2026-09-22 08:15",user:"Baker A",action:"Recorded 2 rejects on BAT-1048",type:"BATCH"},
{time:"2026-09-21 16:20",user:"Production Manager",action:"Created production plan PLAN-2211",type:"CREATE"}]};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}} let db=load(); function save(){localStorage.setItem(KEY,JSON.stringify(db))}
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])); function money(n){return "$"+Number(n||0).toFixed(2)} function product(id){return db.products.find(x=>x.id===id)||{name:id,cost:0,price:0,qc:0}} function toast(msg){const d=document.createElement("div");d.className="toast";d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)} function badge(s){const cls=["ACTIVE","APPROVED","PASSED","COMPLETED"].includes(s)?"good":["TESTING","DEVELOPMENT","PLANNED","PENDING","AWAITING_QC"].includes(s)?"warn":["QC_FAILED","DISCONTINUED"].includes(s)?"bad":"";return '<span class="badge '+cls+'">'+esc(s)+'</span>'}
const navItems=[["dashboard","⌂","Dashboard"],["products","◈","Products"],["recipes","▤","Recipe Bible"],["ingredients","◌","Ingredients"],["suppliers","◇","Suppliers"],["costing","$","Costing"],["production","▦","Production"],["batches","▣","Batch Sheets"],["qc","✓","Quality Control"],["photos","▧","Product Photos"],["reports","◫","Reports"],["versions","↻","Version History"],["settings","⚙","Settings"]];
let route=location.hash.slice(1)||"dashboard";
function shell(){document.querySelector("#app").innerHTML='<div class="app"><aside class="side"><div class="brand"><b>BAKELY</b><small>Product Operating System</small></div><nav class="nav">'+navItems.map(n=>'<button data-route="'+n[0]+'" class="'+(route===n[0]?"active":"")+'"><strong>'+n[1]+'</strong><span>'+n[2]+'</span></button>').join("")+'</nav><div class="sidefoot">Owner / Admin<br>Local data mode · GitHub Pages</div></aside><section class="main"><header class="top"><input id="globalSearch" class="search" placeholder="Search products, recipes, batches, ingredients…"><div class="top-actions"><button class="btn hide-mobile" onclick="quickAdd()">＋ Quick Add</button><button class="btn">♡</button><div class="avatar">P</div></div></header><main class="content" id="view"></main></section></div>';document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>location.hash=b.dataset.route);$("#globalSearch").oninput=e=>{if(e.target.value.trim())renderSearch(e.target.value.trim())}}
function head(k,desc,actions=""){return '<div class="pagehead"><div><div class="eyebrow">BAKELY · '+esc(k)+'</div><h1>'+esc(k)+'</h1><div class="muted">'+esc(desc)+'</div></div><div class="actions">'+actions+'</div></div>'}
function render(){route=location.hash.slice(1)||"dashboard";shell();const v=$("#view");({dashboard,products,recipes,ingredients,suppliers,costing,production,batches,qc,photos,reports,versions,settings}[route]||dashboard)(v)}
function avgQC(){return Math.round(db.qc.reduce((a,q)=>a+q.score,0)/Math.max(1,db.qc.length))} function margin(p){return p.price?((p.price-p.cost)/p.price*100):0}
function timeline(){return '<div class="timeline">'+db.audit.slice(0,6).map(a=>'<div class="event"><b>'+esc(a.action)+'</b><div class="muted">'+esc(a.time)+' · '+esc(a.user)+'</div></div>').join("")+'</div>'}
function productionTable(){return '<div class="tablewrap"><table class="table"><thead><tr><th>Product</th><th>Qty</th><th>Baker</th><th>Status</th></tr></thead><tbody>'+db.plans.filter(p=>p.date==="2026-09-22").map(p=>'<tr><td>'+esc(product(p.product).name)+'</td><td>'+p.qty+'</td><td>'+esc(p.baker)+'</td><td>'+badge(p.status)+'</td></tr>').join("")+'</tbody></table></div>'}
function dashboard(v){const active=db.products.filter(p=>p.status==="ACTIVE").length,pending=db.qc.filter(q=>q.status==="PENDING").length,low=db.ingredients.filter(i=>i.stock<i.min).length,prod=db.plans.filter(p=>p.date==="2026-09-22").reduce((a,p)=>a+p.qty,0);v.innerHTML=head("Dashboard","Your daily operating view.",'<button class="btn primary" onclick="newBatch()">＋ New Batch</button>')+'<div class="grid kpis">'+[['Active Products',active,'+2 this month'],['Today Production',prod,'planned units'],['Pending QC',pending,'needs attention'],['Low Stock',low,'reorder items'],['Avg QC',avgQC()+'%','last 30 days']].map(x=>'<div class="card kpi"><div class="label">'+x[0]+'</div><div class="value">'+x[1]+'</div><div class="trend">'+x[2]+'</div></div>').join("")+'</div><br><div class="grid two"><div class="card"><h3>Today’s Production</h3>'+productionTable()+'</div><div class="card"><h3>Operational Alerts</h3><div class="notice"><b>Supplier price change</b> affects 4 products.</div><div class="notice">BAT-1048 is awaiting QC sign-off.</div><div class="notice">2 ingredients are below reorder level.</div></div></div><br><div class="grid two"><div class="card"><h3>Recent Activity</h3>'+timeline()+'</div><div class="card"><h3>Product Margin Snapshot</h3>'+db.products.slice(0,6).map(p=>'<div style="margin:13px 0"><div style="display:flex;justify-content:space-between"><span>'+esc(p.name)+'</span><b>'+margin(p).toFixed(1)+'%</b></div><div class="bar"><i style="width:'+Math.min(100,margin(p))+'%"></i></div></div>').join("")+'</div></div>'}
function products(v){v.innerHTML=head("Products","The authoritative BAKELY product catalog.",'<button class="btn primary" onclick="productForm()">＋ New Product</button>')+'<div class="toolbar"><input class="search" id="pf" placeholder="Filter products…"><select id="ps"><option value="">All statuses</option><option>ACTIVE</option><option>DEVELOPMENT</option><option>TESTING</option><option>SEASONAL</option></select></div><div class="card tablewrap"><table class="table"><thead><tr><th>Code</th><th>Product</th><th>Category</th><th>Status</th><th>Version</th><th>Cost</th><th>Price</th><th>Margin</th><th>QC</th></tr></thead><tbody id="ptbody">'+productRows(db.products)+'</tbody></table></div>';$("#pf").oninput=filterProducts;$("#ps").onchange=filterProducts}
function productRows(arr){return arr.map(p=>'<tr onclick="productDetail(\''+p.id+'\')" style="cursor:pointer"><td><b>'+p.id+'</b></td><td>'+esc(p.name)+'</td><td>'+esc(p.cat)+'</td><td>'+badge(p.status)+'</td><td>'+p.version+'</td><td>'+money(p.cost)+'</td><td>'+money(p.price)+'</td><td>'+margin(p).toFixed(1)+'%</td><td>'+p.qc+'%</td></tr>').join("")}
function filterProducts(){const q=$("#pf").value.toLowerCase(),s=$("#ps").value;$("#ptbody").innerHTML=productRows(db.products.filter(p=>(!q||(p.name+p.id+p.cat).toLowerCase().includes(q))&&(!s||p.status===s)))}
function productDetail(id){const p=product(id),r=db.recipes.find(x=>x.product===id);$("#view").innerHTML=head(p.name,p.id+" · "+p.collection,'<button class="btn" onclick="productForm(\''+id+'\')">Edit</button><button class="btn primary" onclick="recipeForm(\''+id+'\')">＋ Recipe Version</button>')+'<div class="grid three"><div class="card"><div class="eyebrow">Unit Cost</div><div class="score">'+money(p.cost)+'</div><div class="muted">Current costing</div></div><div class="card"><div class="eyebrow">Margin</div><div class="score">'+margin(p).toFixed(1)+'%</div><div class="muted">Selling price '+money(p.price)+'</div></div><div class="card"><div class="eyebrow">QC</div><div class="score">'+p.qc+'%</div><div class="muted">Product standard</div></div></div><br><div class="grid two"><div class="card"><h3>Product DNA</h3><p>Premium artisan product with a consistent visual, flavour and texture standard.</p><div class="formgrid"><div><b>Effort</b><p>'+p.effort+'/5</p></div><div><b>Current Recipe</b><p>'+esc(r?.version||p.version)+'</p></div><div><b>Category</b><p>'+esc(p.cat)+'</p></div><div><b>Status</b><p>'+badge(p.status)+'</p></div></div></div><div class="card"><h3>Visual Standard</h3><div class="heroimage"><div class="cookiebig"></div></div><p class="muted">Target: golden edge, soft centre, natural cracks, generous inclusions.</p></div></div>'}
function productForm(id){const p=id?product(id):{id:"",name:"",cat:"Cookie",collection:"BAKELY Classics",status:"DEVELOPMENT",version:"V0.1",cost:0,price:0,effort:3,qc:90};modal("Product",'<div class="formgrid"><div class="field"><label>Product Code</label><input id="f_id" value="'+esc(p.id)+'" '+(id?"disabled":"")+'></div><div class="field"><label>Name</label><input id="f_name" value="'+esc(p.name)+'"></div><div class="field"><label>Category</label><select id="f_cat"><option>Cookie</option><option>Brownie</option><option>Gift Box</option></select></div><div class="field"><label>Collection</label><input id="f_col" value="'+esc(p.collection)+'"></div><div class="field"><label>Status</label><select id="f_status">'+["IDEA","DEVELOPMENT","TESTING","APPROVED","ACTIVE","SEASONAL","DISCONTINUED"].map(x=>'<option '+(x===p.status?"selected":"")+'>'+x+'</option>').join("")+'</select></div><div class="field"><label>Selling Price</label><input id="f_price" type="number" step=".01" value="'+p.price+'"></div><div class="field"><label>Unit Cost</label><input id="f_cost" type="number" step=".01" value="'+p.cost+'"></div><div class="field"><label>Effort 1–5</label><input id="f_effort" type="number" min="1" max="5" value="'+p.effort+'"></div></div>','Save Product',()=>{const n={...p,id:$("#f_id").value.trim(),name:$("#f_name").value.trim(),cat:$("#f_cat").value,collection:$("#f_col").value.trim(),status:$("#f_status").value,price:+$("#f_price").value,cost:+$("#f_cost").value,effort:+$("#f_effort").value};if(!n.id||!n.name)return toast("Code and name are required");if(!id&&db.products.some(x=>x.id===n.id))return toast("Product code already exists");if(id)Object.assign(p,n);else{n.qc=95;n.version="V0.1";db.products.push(n)}db.audit.unshift({time:new Date().toISOString().slice(0,16).replace("T"," "),user:"Owner",action:(id?"Updated ":"Created ")+n.id,type:id?"UPDATE":"CREATE"});save();closeModal();toast("Product saved");render()})}
function recipes(v){v.innerHTML=head("Recipe Bible","Approved formulas, process standards and immutable versions.",'<button class="btn primary" onclick="recipeForm()">＋ New Recipe</button>')+'<div class="notice"><b>Rule:</b> Approved recipes are immutable. Changes create a new version and preserve historical costing.</div><div class="card tablewrap"><table class="table"><thead><tr><th>Recipe</th><th>Product</th><th>Version</th><th>Status</th><th>Yield</th><th>Unit Weight</th><th>Created</th><th></th></tr></thead><tbody>'+db.recipes.map(r=>'<tr><td><b>'+r.id+'</b></td><td>'+esc(product(r.product).name)+'</td><td>'+r.version+'</td><td>'+badge(r.status)+'</td><td>'+r.yield+'</td><td>'+r.unitWeight+'g</td><td>'+r.created+'</td><td><button class="btn" onclick="recipeDetail(\''+r.id+'\')">Open</button></td></tr>').join("")+'</tbody></table></div>'}
function recipeDetail(id){const r=db.recipes.find(x=>x.id===id),p=product(r.product);const ing=r.ingredients.map(([iid,q])=>{const i=db.ingredients.find(x=>x.id===iid),unit=i?.unit||"g",c=i?i.price/i.pack*q:0;return '<tr><td>'+esc(i?.name||iid)+'</td><td>'+q+'</td><td>'+unit+'</td><td>'+((q/(r.ingredients.find(x=>x[0]==="ING-001")?.[1]||500))*100).toFixed(1)+'%</td><td>'+money(c)+'</td></tr>'}).join("");$("#view").innerHTML=head("Recipe "+r.version,p.name+" · "+r.id,'<button class="btn" onclick="recipeForm(\''+p.id+'\')">Create New Version</button><button class="btn primary" onclick="approveRecipe(\''+r.id+'\')">Approve</button>')+'<div class="grid two"><div class="card"><h3>Formula</h3><div class="tablewrap"><table class="table"><tr><th>Ingredient</th><th>Qty</th><th>Unit</th><th>Baker %</th><th>Cost</th></tr>'+ing+'</table></div><p class="muted">Scaling preserves baker percentages and target unit weight.</p></div><div class="card"><h3>Production Method</h3><ol>'+r.method.map(x=>'<li>'+esc(x)+'</li>').join("")+'</ol><div class="notice"><b>Critical controls:</b> portion '+r.unitWeight+'g · bake target 175°C · cool completely before packaging.</div></div></div><br><div class="card"><h3>Version Record</h3><p><b>'+r.version+'</b> · '+r.status+' · '+r.created+'</p><p>'+esc(r.reason)+'</p></div>'}
function recipeForm(productId){const p=productId?product(productId):db.products[0];modal("New Recipe Version",'<div class="formgrid"><div class="field"><label>Product</label><select id="rf_product">'+db.products.map(x=>'<option value="'+x.id+'" '+(x.id===p.id?"selected":"")+'>'+esc(x.name)+'</option>').join("")+'</select></div><div class="field"><label>Version</label><input id="rf_ver" value="V1.1"></div><div class="field"><label>Yield</label><input id="rf_yield" type="number" value="10"></div><div class="field"><label>Unit Weight (g)</label><input id="rf_weight" type="number" value="75"></div><div class="field full"><label>Method</label><textarea id="rf_method">Prepare ingredients.\nMix according to approved process.\nPortion.\nBake.\nCool.\nPackage.</textarea></div><div class="field full"><label>Change Reason</label><textarea id="rf_reason">New recipe development version.</textarea></div></div>','Save Draft',()=>{const n={id:"RCP-"+String(Date.now()).slice(-6),product:$("#rf_product").value,version:$("#rf_ver").value,status:"DRAFT",yield:+$("#rf_yield").value,unitWeight:+$("#rf_weight").value,ingredients:[["ING-001",500],["ING-002",300],["ING-003",200]],method:$("#rf_method").value.split("\n").filter(Boolean),created:new Date().toISOString().slice(0,10),reason:$("#rf_reason").value};db.recipes.push(n);db.audit.unshift({time:new Date().toISOString().slice(0,16).replace("T"," "),user:"Owner",action:"Created recipe "+n.id+" "+n.version,type:"CREATE"});save();closeModal();toast("Recipe draft created");render()})}
function approveRecipe(id){const r=db.recipes.find(x=>x.id===id);if(!r)return;db.recipes.filter(x=>x.product===r.product&&x.status==="APPROVED").forEach(x=>x.status="SUPERSEDED");r.status="APPROVED";const p=product(r.product);p.version=r.version;db.audit.unshift({time:new Date().toISOString().slice(0,16).replace("T"," "),user:"Owner",action:"Approved "+r.id+" "+r.version,type:"APPROVE"});save();toast("Recipe approved");recipeDetail(id)}
function ingredients(v){v.innerHTML=head("Ingredients","Master ingredient catalog and supplier pricing.",'<button class="btn primary" onclick="ingredientForm()">＋ Add Ingredient</button>')+'<div class="card tablewrap"><table class="table"><thead><tr><th>SKU</th><th>Ingredient</th><th>Supplier</th><th>Pack</th><th>Price</th><th>Cost / unit</th><th>Stock</th><th>State</th></tr></thead><tbody>'+db.ingredients.map(i=>'<tr><td>'+i.id+'</td><td>'+esc(i.name)+'</td><td>'+esc(i.supplier)+'</td><td>'+i.pack+i.unit+'</td><td>'+money(i.price)+'</td><td>'+money(i.price/i.pack)+' / '+i.unit+'</td><td>'+i.stock+i.unit+'</td><td>'+(i.stock<i.min?'<span class="badge bad">REORDER</span>':'<span class="badge good">OK</span>')+'</td></tr>').join("")+'</tbody></table></div>'}
function ingredientForm(){modal("Add Ingredient",'<div class="formgrid"><div class="field"><label>SKU</label><input id="if_id" value="ING-'+String(Date.now()).slice(-4)+'"></div><div class="field"><label>Name</label><input id="if_name"></div><div class="field"><label>Base Unit</label><select id="if_unit"><option>g</option><option>ml</option><option>unit</option></select></div><div class="field"><label>Pack Size</label><input id="if_pack" type="number"></div><div class="field"><label>Purchase Price</label><input id="if_price" type="number" step=".01"></div><div class="field"><label>Supplier</label><input id="if_sup" value="BAKELY Ingredients Co."></div><div class="field"><label>Opening Stock</label><input id="if_stock" type="number" value="0"></div><div class="field"><label>Reorder Point</label><input id="if_min" type="number" value="0"></div></div>','Save Ingredient',()=>{const i={id:$("#if_id").value,name:$("#if_name").value,unit:$("#if_unit").value,pack:+$("#if_pack").value,price:+$("#if_price").value,supplier:$("#if_sup").value,stock:+$("#if_stock").value,min:+$("#if_min").value};if(!i.name||!i.pack||!i.price)return toast("Complete required fields");db.ingredients.push(i);db.audit.unshift({time:new Date().toISOString().slice(0,16).replace("T"," "),user:"Owner",action:"Added ingredient "+i.id,type:"CREATE"});save();closeModal();toast("Ingredient added");render()})}
function suppliers(v){v.innerHTML=head("Suppliers","Supplier directory, lead times and commercial terms.",'<button class="btn primary" onclick="supplierForm()">＋ Add Supplier</button>')+'<div class="grid three">'+db.suppliers.map(s=>'<div class="card"><div class="eyebrow">'+s.id+'</div><h3>'+esc(s.name)+'</h3><p>'+esc(s.contact)+' · '+esc(s.email)+'</p><p><b>Lead:</b> '+esc(s.lead)+'<br><b>Terms:</b> '+esc(s.terms)+'</p>'+badge(s.status)+'</div>').join("")+'</div>'}
function supplierForm(){modal("Add Supplier",'<div class="formgrid"><div class="field"><label>Company</label><input id="sf_name"></div><div class="field"><label>Contact</label><input id="sf_contact"></div><div class="field"><label>Email</label><input id="sf_email" type="email"></div><div class="field"><label>Lead Time</label><input id="sf_lead" value="3 days"></div><div class="field"><label>Payment Terms</label><input id="sf_terms" value="Net 30"></div></div>','Save Supplier',()=>{const s={id:"SUP-"+String(Date.now()).slice(-4),name:$("#sf_name").value,contact:$("#sf_contact").value,email:$("#sf_email").value,lead:$("#sf_lead").value,terms:$("#sf_terms").value,status:"ACTIVE"};if(!s.name)return toast("Company required");db.suppliers.push(s);save();closeModal();toast("Supplier added");render()})}
function costing(v){const rows=db.products.map(p=>'<tr><td>'+p.id+'</td><td>'+esc(p.name)+'</td><td>'+money(p.cost)+'</td><td>'+money(p.price)+'</td><td>'+money(p.price-p.cost)+'</td><td><b>'+margin(p).toFixed(1)+'%</b></td></tr>').join("");v.innerHTML=head("Costing","Transparent true-cost and margin management.",'<button class="btn gold" onclick="whatIf()">What-if Costing</button>')+'<div class="grid three"><div class="card"><div class="eyebrow">Average Unit Cost</div><div class="score">'+money(db.products.reduce((a,p)=>a+p.cost,0)/db.products.length)+'</div></div><div class="card"><div class="eyebrow">Average Margin</div><div class="score">'+(db.products.reduce((a,p)=>a+margin(p),0)/db.products.length).toFixed(1)+'%</div></div><div class="card"><div class="eyebrow">Price Changes</div><div class="score">1</div><div class="muted">this week</div></div></div><br><div class="card"><h3>Product Profitability</h3><div class="tablewrap"><table class="table"><tr><th>Code</th><th>Product</th><th>Unit Cost</th><th>Price</th><th>Gross Profit</th><th>Margin</th></tr>'+rows+'</table></div></div>'}
function whatIf(){modal("What-if Costing",'<div class="field"><label>Chocolate price increase %</label><input id="wi" type="number" value="15"></div><br><div class="notice">Simulation only. Live prices and selling prices will not be changed.</div><div id="wo"></div>','Close',()=>closeModal());setTimeout(()=>{$("#wi").oninput=calcWhatIf;calcWhatIf()},0)}
function calcWhatIf(){const pct=+$("#wi").value/100;$("#wo").innerHTML=db.products.filter(p=>p.id.startsWith("CK")||p.id.startsWith("BW")).map(p=>{const extra=p.cost*.18*pct,newc=p.cost+extra;return '<p><b>'+esc(p.name)+'</b>: '+money(p.cost)+' → '+money(newc)+' · margin '+margin(p).toFixed(1)+'% → '+((p.price-newc)/p.price*100).toFixed(1)+'%</p>'}).join("")}
function production(v){v.innerHTML=head("Production Planning","Plan demand, assign bakers and monitor capacity.",'<button class="btn primary" onclick="planForm()">＋ Production Plan</button>')+'<div class="card"><h3>September 2026</h3><div class="calendar">'+["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=>'<div class="day"><b>'+x+'</b></div>').join("")+Array.from({length:14},(_,i)=>{const d=String(19+i).padStart(2,"0"),ds="2026-09-"+d;return '<div class="day"><b>'+d+'</b>'+db.plans.filter(p=>p.date===ds).map(p=>'<div class="mini">'+p.product+' · '+p.qty+'</div>').join("")+'</div>'}).join("")+'</div></div><br><div class="card"><h3>Production Queue</h3>'+productionTable()+'</div>'}
function planForm(){modal("Production Plan",'<div class="formgrid"><div class="field"><label>Date</label><input id="pl_date" type="date" value="2026-09-24"></div><div class="field"><label>Product</label><select id="pl_prod">'+db.products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("")+'</select></div><div class="field"><label>Quantity</label><input id="pl_qty" type="number" value="50"></div><div class="field"><label>Baker</label><input id="pl_baker" value="Baker A"></div><div class="field"><label>Due</label><input id="pl_due" type="time" value="12:00"></div><div class="field"><label>Priority</label><select id="pl_pr"><option>Normal</option><option>High</option><option>Urgent</option></select></div></div>','Create Plan',()=>{const p={id:"PLAN-"+String(Date.now()).slice(-5),date:$("#pl_date").value,product:$("#pl_prod").value,qty:+$("#pl_qty").value,baker:$("#pl_baker").value,due:$("#pl_due").value,status:"PLANNED",priority:$("#pl_pr").value};db.plans.push(p);db.audit.unshift({time:new Date().toISOString().slice(0,16).replace("T"," "),user:"Owner",action:"Created production plan "+p.id,type:"CREATE"});save();closeModal();toast("Production plan created");render()})}
function batches(v){v.innerHTML=head("Batch Sheets","Traceable production records generated from approved recipes.",'<button class="btn primary" onclick="newBatch()">＋ New Batch</button>')+'<div class="card tablewrap"><table class="table"><thead><tr><th>Batch</th><th>Product</th><th>Recipe</th><th>Qty</th><th>Baker</th><th>Date</th><th>Status</th><th></th></tr></thead><tbody>'+db.batches.map(b=>'<tr><td><b>'+b.id+'</b></td><td>'+esc(product(b.product).name)+'</td><td>'+b.recipe+'</td><td>'+b.qty+'</td><td>'+esc(b.baker)+'</td><td>'+b.date+'</td><td>'+badge(b.status)+'</td><td><button class="btn" onclick="batchDetail(\''+b.id+'\')">Open</button></td></tr>').join("")+'</tbody></table></div>'}
function newBatch(){modal("New Batch",'<div class="formgrid"><div class="field"><label>Product</label><select id="bf_prod">'+db.products.filter(p=>p.status==="ACTIVE").map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("")+'</select></div><div class="field"><label>Quantity</label><input id="bf_qty" type="number" value="50"></div><div class="field"><label>Baker</label><input id="bf_baker" value="Baker A"></div><div class="field"><label>Date</label><input id="bf_date" type="date" value="2026-09-22"></div></div>','Generate Batch Sheet',()=>{const pid=$("#bf_prod").value,r=db.recipes.find(x=>x.product===pid&&x.status==="APPROVED");if(!r)return toast("No approved recipe for this product");const b={id:"BAT-"+String(Date.now()).slice(-5),product:pid,recipe:r.version,qty:+$("#bf_qty").value,baker:$("#bf_baker").value,date:$("#bf_date").value,status:"READY",yield:0,waste:0};db.batches.push(b);db.audit.unshift({time:new Date().toISOString().slice(0,16).replace("T"," "),user:"Owner",action:"Generated batch "+b.id+" from "+r.version,type:"CREATE"});save();closeModal();toast("Batch sheet generated");render()})}
function batchDetail(id){const b=db.batches.find(x=>x.id===id),p=product(b.product),r=db.recipes.find(x=>x.product===b.product&&x.version===b.recipe);$("#view").innerHTML=head("Batch "+b.id,p.name+" · Recipe "+b.recipe,'<button class="btn" onclick="print()">Print</button><button class="btn primary" onclick="startBatch(\''+id+'\')">Update Batch</button>')+'<div class="grid three"><div class="card"><div class="eyebrow">Planned</div><div class="score">'+b.qty+'</div><div class="muted">units</div></div><div class="card"><div class="eyebrow">Actual Yield</div><div class="score">'+b.yield+'</div><div class="muted">saleable units</div></div><div class="card"><div class="eyebrow">Status</div><div style="margin-top:15px">'+badge(b.status)+'</div></div></div><br><div class="grid two"><div class="card"><h3>Scaled Ingredients</h3><table class="table"><tr><th>Ingredient</th><th>Planned</th><th>Actual</th></tr>'+r.ingredients.map(([iid,q])=>'<tr><td>'+esc(db.ingredients.find(i=>i.id===iid)?.name||iid)+'</td><td>'+((q/r.yield)*b.qty).toFixed(1)+'g</td><td>—</td></tr>').join("")+'</table></div><div class="card"><h3>Production Controls</h3><ol>'+r.method.map(x=>'<li>'+esc(x)+'</li>').join("")+'</ol><div class="notice">Record actual temperatures, times, yield and waste on completion.</div></div></div>'}
function startBatch(id){const b=db.batches.find(x=>x.id===id);modal("Update Batch",'<div class="formgrid"><div class="field"><label>Status</label><select id="ub_status">'+["READY","IN_PROGRESS","AWAITING_QC","COMPLETED"].map(x=>'<option '+(x===b.status?"selected":"")+'>'+x+'</option>').join("")+'</select></div><div class="field"><label>Actual Saleable Yield</label><input id="ub_yield" type="number" value="'+b.yield+'"></div><div class="field"><label>Waste Units</label><input id="ub_waste" type="number" value="'+b.waste+'"></div><div class="field full"><label>Production Notes</label><textarea id="ub_notes"></textarea></div></div>','Save Batch',()=>{b.status=$("#ub_status").value;b.yield=+$("#ub_yield").value;b.waste=+$("#ub_waste").value;if(b.status==="COMPLETED"){const q=db.qc.find(x=>x.batch===b.id);if(!q||q.status!=="PASSED")return toast("QC sign-off is required before completion")}db.audit.unshift({time:new Date().toISOString().slice(0,16).replace("T"," "),user:"Owner",action:"Updated batch "+b.id+" to "+b.status,type:"UPDATE"});save();closeModal();toast("Batch updated");render()})}
function qc(v){v.innerHTML=head("Quality Control","Inspect every production batch against BAKELY standards.",'<button class="btn primary" onclick="qcForm()">＋ QC Inspection</button>')+'<div class="grid three">'+db.qc.map(q=>'<div class="card"><div style="display:flex;justify-content:space-between"><b>'+q.id+'</b>'+badge(q.status)+'</div><h3>'+esc(product(db.batches.find(b=>b.id===q.batch)?.product||q.product).name)+'</h3><div class="score">'+q.score+'%</div><p>'+esc(q.notes)+'</p><small class="muted">'+esc(q.tester)+'</small></div>').join("")+'</div>'}
function qcForm(){modal("QC Inspection",'<div class="formgrid"><div class="field"><label>Batch</label><select id="q_batch">'+db.batches.map(b=>'<option value="'+b.id+'">'+b.id+' · '+product(b.product).name+'</option>').join("")+'</select></div><div class="field"><label>Score</label><input id="q_score" type="number" min="0" max="100" value="96"></div><div class="field"><label>Status</label><select id="q_status"><option>PASSED</option><option>PENDING</option><option>QC_FAILED</option></select></div><div class="field full"><label>Notes</label><textarea id="q_notes">Appearance, weight, texture and taste checked.</textarea></div></div>','Save QC',()=>{const b=db.batches.find(x=>x.id===$("#q_batch").value),q={id:"QC-"+String(Date.now()).slice(-5),batch:b.id,product:b.product,score:+$("#q_score").value,status:$("#q_status").value,tester:"Owner",notes:$("#q_notes").value};db.qc.unshift(q);if(q.status==="PASSED"){b.status="COMPLETED";b.yield=b.yield||b.qty}db.audit.unshift({time:new Date().toISOString().slice(0,16).replace("T"," "),user:"Owner",action:"Recorded QC "+q.id+" for "+b.id,type:"QC_SIGNOFF"});save();closeModal();toast("QC recorded");render()})}
function photos(v){v.innerHTML=head("Product Photos","Visual standards and production reference library.",'<button class="btn primary" onclick="photoForm()">＋ Add Photo Record</button>')+'<div class="grid three">'+db.photos.map(ph=>'<div class="card"><div class="photo"><div class="cookiebig"></div><small>'+esc(ph.type)+'</small></div><h3>'+esc(product(ph.product).name)+'</h3><p class="muted">'+esc(ph.caption)+'</p></div>').join("")+'</div><div class="notice">GitHub Pages is static. V1 stores photo metadata locally; connect object storage for shared image uploads.</div>'}
function photoForm(){modal("Photo Record",'<div class="formgrid"><div class="field"><label>Product</label><select id="ph_prod">'+db.products.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join("")+'</select></div><div class="field"><label>Photo Type</label><select id="ph_type"><option>Hero</option><option>Top</option><option>Side</option><option>Cross-section</option><option>Packaging</option><option>Process</option><option>QC</option><option>Gift</option></select></div><div class="field full"><label>Caption</label><input id="ph_cap" value="Approved visual reference"></div></div>','Save Photo Record',()=>{db.photos.push({id:"PH-"+String(Date.now()).slice(-5),product:$("#ph_prod").value,type:$("#ph_type").value,caption:$("#ph_cap").value});save();closeModal();toast("Photo record saved");render()})}
function reports(v){const totalUnits=db.batches.reduce((a,b)=>a+(b.yield||0),0),waste=db.batches.reduce((a,b)=>a+(b.waste||0),0);v.innerHTML=head("Reports","Management views across cost, production, yield and quality.",'<button class="btn" onclick="exportCSV()">Export CSV</button>')+'<div class="grid three"><div class="card"><div class="eyebrow">Saleable Units</div><div class="score">'+totalUnits+'</div></div><div class="card"><div class="eyebrow">Waste Units</div><div class="score">'+waste+'</div></div><div class="card"><div class="eyebrow">Yield Rate</div><div class="score">'+(totalUnits/(totalUnits+waste||1)*100).toFixed(1)+'%</div></div></div><br><div class="grid two"><div class="card"><h3>Product Profitability</h3><div class="tablewrap"><table class="table"><tr><th>Code</th><th>Product</th><th>Cost</th><th>Price</th><th>Margin</th></tr>'+db.products.map(p=>'<tr><td>'+p.id+'</td><td>'+esc(p.name)+'</td><td>'+money(p.cost)+'</td><td>'+money(p.price)+'</td><td>'+margin(p).toFixed(1)+'%</td></tr>').join("")+'</table></div></div><div class="card"><h3>QC Performance</h3>'+db.qc.map(q=>'<p><b>'+q.id+'</b> · '+q.score+'% · '+badge(q.status)+'</p>').join("")+'</div></div>'}
function exportCSV(){const rows=[["Code","Product","Cost","Price","Margin"],...db.products.map(p=>[p.id,p.name,p.cost,p.price,margin(p).toFixed(2)])];const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(",")).join("\n"),blob=new Blob([csv],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="bakely-product-profitability.csv";a.click();URL.revokeObjectURL(a.href);toast("CSV exported")}
function versions(v){v.innerHTML=head("Version History","Immutable operational audit trail.",'<button class="btn" onclick="location.hash=\'recipes\'">Recipe Bible</button>')+'<div class="card"><div class="timeline">'+db.audit.map(a=>'<div class="event"><b>'+esc(a.action)+'</b><div>'+esc(a.type)+' · '+esc(a.user)+' · '+esc(a.time)+'</div></div>').join("")+'</div></div>'}
function settings(v){v.innerHTML=head("Settings","BAKELY business configuration and data controls.")+'<div class="grid two"><div class="card"><h3>Business Defaults</h3><div class="formgrid"><div class="field"><label>Business Name</label><input value="BAKELY"></div><div class="field"><label>Currency</label><select><option>USD</option><option>AED</option><option>INR</option></select></div><div class="field"><label>Default Waste %</label><input value="3"></div><div class="field"><label>Target Margin %</label><input value="70"></div><div class="field"><label>Timezone</label><input value="Asia/Dubai"></div></div></div><div class="card"><h3>Data Controls</h3><p class="muted">This GitHub Pages build uses browser localStorage. It is not a shared production database.</p><button class="btn" onclick="downloadBackup()">Download JSON Backup</button> <button class="btn danger" onclick="resetDemo()">Reset Demo Data</button></div></div><br><div class="card"><h3>Platform Roadmap</h3><p>Next backend stage: shared authentication, database, object storage, server-side audit logs and multi-user synchronization.</p></div>'}
function downloadBackup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="bakely-pos-backup.json";a.click();URL.revokeObjectURL(a.href);toast("Backup downloaded")}
function resetDemo(){if(confirm("Reset all browser data to BAKELY demo data?")){db=structuredClone(seed);save();render();toast("Demo data reset")}}
function renderSearch(q){const hits=[...db.products.map(x=>({type:"Product",id:x.id,name:x.name})),...db.ingredients.map(x=>({type:"Ingredient",id:x.id,name:x.name})),...db.recipes.map(x=>({type:"Recipe",id:x.id,name:x.version+" · "+product(x.product).name})),...db.batches.map(x=>({type:"Batch",id:x.id,name:x.id+" · "+product(x.product).name}))].filter(x=>(x.id+" "+x.name).toLowerCase().includes(q.toLowerCase()));$("#view").innerHTML=head("Search","Results for “"+q+"”")+'<div class="card"><table class="table"><tr><th>Type</th><th>ID</th><th>Name</th></tr>'+hits.map(h=>'<tr><td>'+h.type+'</td><td>'+h.id+'</td><td>'+esc(h.name)+'</td></tr>').join("")+'</table></div>'}
function modal(title,body,button,fn){const d=document.createElement("div");d.className="modal";d.id="modal";d.innerHTML='<div class="modalbox"><div class="modalhead"><h2>'+esc(title)+'</h2><button class="close" onclick="closeModal()">×</button></div>'+body+'<div class="actions" style="justify-content:flex-end;margin-top:20px"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" id="modalSave">'+esc(button)+'</button></div></div>';document.body.appendChild(d);$("#modalSave").onclick=fn}
function closeModal(){$("#modal")?.remove()}
function quickAdd(){modal("Quick Add",'<div class="grid three">'+[["Product","productForm"],["Recipe","recipeForm"],["Ingredient","ingredientForm"],["Supplier","supplierForm"],["Production Plan","planForm"],["Batch","newBatch"],["QC","qcForm"],["Photo","photoForm"]].map(x=>'<button class="card btn" style="text-align:left" onclick="closeModal();'+x[1]+'()"><b>＋ '+x[0]+'</b></button>').join("")+'</div>',"Close",closeModal)}
Object.assign(window,{productDetail,productForm,recipeDetail,recipeForm,approveRecipe,ingredientForm,supplierForm,whatIf,planForm,newBatch,batchDetail,startBatch,qcForm,photoForm,exportCSV,downloadBackup,resetDemo,quickAdd,closeModal});
window.addEventListener("hashchange",render);render();